org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
flutter.compileSdkVersion=36
flutter.minSdkVersion=24
flutter.targetSdkVersion=34
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
# Evita fallos de rutas relativas cuando el proyecto y la cache de Pub estan
# en unidades distintas (por ejemplo, E: y C:) en Windows.
kotlin.incremental=false
